services:
  db:
    build: database
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent']
      interval: 2s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_DATABASE=film
      - MYSQL_ROOT_PASSWORD=film
    expose:
      - 3306
      - 33060

  flask:
    stdin_open: true
    tty: true
    build: flask
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy

  # phpmyadmin:
  #     image: phpmyadmin/phpmyadmin:latest
  #     container_name: 'Phpmyadmin'
  #     links:
  #       - db
  #     environment:
  #       PMA_HOST: db
  #       PMA_PORT: 3306
  #     ports:
  #       - '800:80'



volumes:
  mysql_data: