services:
  db:
    build: database
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent']
      interval: 2s
      retries: 5
      start_period: 60s
    environment:
      - MYSQL_DATABASE=films
      - MYSQL_ROOT_PASSWORD=film
    expose:
      - 3306
      - 33060

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOSTS: db

  backend:
    stdin_open: true
    tty: true
    build: backend
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    expose:
      - 5000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    stdin_open: true
    tty: true
    build: frontend
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    expose:
      - 8000
    depends_on:
      backend:
        condition: service_started

volumes:
  mysql_data:
